### ISSUE TITLE
Transfer learning or Append new training dataset

### ISSUE THREAD

**Issue by mudasar477** [srp98/Movie-Recommender-using-RBM#1]
Is there a way that we perform transfer learning or save weights of 1 training and next time append these weights with new dataset.

I am facing issue while training large amount of data it gives me memory error.

Thanks in advance

**Comment by srp98** [comment]
transfer learning is possible but the network structure for the saved weights in new model should be same.

When large amount of data, you would wanna make it into batches and feed into the network. If you are using pandas for reading data, change the formats of features to save memory and after performing some transformations convert it to feather format for faster reading of said files.
